# Generated by Django 5.0.6 on 2024-06-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('general_director', 'Генеральный директор'), ('chief_accountant', 'Главный бухгалтер'), ('storekeeper', 'Кладовщик'), ('executive_director', 'Исполнительный директор')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chief_accountant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts_as_chief_accountant', to='inventory.employee')),
                ('executive_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts_as_executive_director', to='inventory.employee')),
                ('general_director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts_as_general_director', to='inventory.employee')),
                ('storekeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acts_as_storekeeper', to='inventory.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WriteOffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.writeoffact')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
            ],
        ),
    ]
